###
# List of products
GET https://nodejs-esgi-server.herokuapp.com/products

###
# One product
GET http://127.0.0.1:3000/products/Coca

###
# Add product
POST http://127.0.0.1:3000/products/add
content-type: application/json

{
    "name": "Coca-coca",
    "quantity": 2
}

###
# Delete product
DELETE https://nodejs-esgi-server.herokuapp.com/products/zizi?quantity=100000000000







###
# List of products
GET https://product-esgi.herokuapp.com/products

###
# One product
GET http://127.0.0.1:3000/products/Coca-Cola

###
# Add product
POST https://product-esgi.herokuapp.com/products
content-type: application/json

{
    "name": "az",
    "quantity": 1
}

###
# Delete product
DELETE https://product-esgi.herokuapp.com/products/zizi?quantity=10